name 'TestRepo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures TestRepo'
long_description 'Installs/Configures TestRepo'
version '0.1.0'
